// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMembers = `-- name: AddGroupMembers :one
insert into conversation_members (conversation_id, user_id, role)
select $1, $2, 'member'
where exists (
    select 1 from conversation_members cm
    where cm.conversation_id = $1 and cm.user_id = $3 and cm.role = 'admin'
)
returning conversation_id, user_id, role
`

type AddGroupMembersParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         int32     `json:"user_id"`
	UserID_2       int32     `json:"user_id_2"`
}

type AddGroupMembersRow struct {
	ConversationID uuid.UUID  `json:"conversation_id"`
	UserID         int32      `json:"user_id"`
	Role           MemberRole `json:"role"`
}

func (q *Queries) AddGroupMembers(ctx context.Context, arg AddGroupMembersParams) (AddGroupMembersRow, error) {
	row := q.db.QueryRow(ctx, addGroupMembers, arg.ConversationID, arg.UserID, arg.UserID_2)
	var i AddGroupMembersRow
	err := row.Scan(&i.ConversationID, &i.UserID, &i.Role)
	return i, err
}

const deleteUserStatus = `-- name: DeleteUserStatus :exec
delete from user_status where user_id = $1
`

func (q *Queries) DeleteUserStatus(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserStatus, userID)
	return err
}

const getDisabledUser = `-- name: GetDisabledUser :one
select user_id, status, updated_at from user_status where user_id = $1
`

func (q *Queries) GetDisabledUser(ctx context.Context, userID int32) (UserStatus, error) {
	row := q.db.QueryRow(ctx, getDisabledUser, userID)
	var i UserStatus
	err := row.Scan(&i.UserID, &i.Status, &i.UpdatedAt)
	return i, err
}

const leaveConversation = `-- name: LeaveConversation :one
delete from conversation_members
where conversation_id = $1 and user_id = $2
returning conversation_id, user_id
`

type LeaveConversationParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         int32     `json:"user_id"`
}

type LeaveConversationRow struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         int32     `json:"user_id"`
}

func (q *Queries) LeaveConversation(ctx context.Context, arg LeaveConversationParams) (LeaveConversationRow, error) {
	row := q.db.QueryRow(ctx, leaveConversation, arg.ConversationID, arg.UserID)
	var i LeaveConversationRow
	err := row.Scan(&i.ConversationID, &i.UserID)
	return i, err
}

const removeGroupMembers = `-- name: RemoveGroupMembers :exec
delete from conversation_members cm
where cm.conversation_id = $1 and cm.user_id = $2
and exists (
    select 1 from conversation_members cm
    where cm.conversation_id = $1 and cm.user_id = $3 and cm.role = 'admin'
)
`

type RemoveGroupMembersParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         int32     `json:"user_id"`
	UserID_2       int32     `json:"user_id_2"`
}

func (q *Queries) RemoveGroupMembers(ctx context.Context, arg RemoveGroupMembersParams) error {
	_, err := q.db.Exec(ctx, removeGroupMembers, arg.ConversationID, arg.UserID, arg.UserID_2)
	return err
}

const saveUserStatus = `-- name: SaveUserStatus :execresult
insert into user_status (
    user_id,
    status,
    updated_at
)
values ($1, $2, $3)
on conflict (user_id)
do update set
    status = excluded.status,
    updated_at = excluded.updated_at
where user_status.updated_at < excluded.updated_at
`

type SaveUserStatusParams struct {
	UserID    int32     `json:"user_id"`
	Status    int16     `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) SaveUserStatus(ctx context.Context, arg SaveUserStatusParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, saveUserStatus, arg.UserID, arg.Status, arg.UpdatedAt)
}

const updateGroupInfo = `-- name: UpdateGroupInfo :one

update groups set 
    name = coalesce($2, name),
    avatar_url = coalesce($3, avatar_url)
where conversation_id = $1
returning conversation_id, name, avatar_url, created_at
`

type UpdateGroupInfoParams struct {
	ConversationID uuid.UUID   `json:"conversation_id"`
	Name           pgtype.Text `json:"name"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
}

// -- name: GetGroupMembers :many
// select
//
//	u.uuid,
//	coalesce(p.name, u.display_name) as name,
//	p.avatar_url,
//	cm.role
//
// from conversation_members cm
// join users u on cm.user_id = u.user_id
// left join profiles p on u.user_id = p.user_id
// where cm.conversation_id = $1
// order by coalesce(p.name, u.display_name);
func (q *Queries) UpdateGroupInfo(ctx context.Context, arg UpdateGroupInfoParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroupInfo, arg.ConversationID, arg.Name, arg.AvatarUrl)
	var i Group
	err := row.Scan(
		&i.ConversationID,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}
