// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	ActiveUser(ctx context.Context, userID int32) (pgconn.CommandTag, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateUser(ctx context.Context, displayName string) (int32, error)
	DeleteUser(ctx context.Context, userID int32) (pgconn.CommandTag, error)
	DisableUser(ctx context.Context, userID int32) error
	GetProfile(ctx context.Context, userID int32) (GetProfileRow, error)
	GetProfileByUserId(ctx context.Context, arg GetProfileByUserIdParams) (GetProfileByUserIdRow, error)
	GetUUIDByUserId(ctx context.Context, userID int32) (uuid.UUID, error)
	GetUserByUUID(ctx context.Context, targetUserUuid uuid.UUID) (GetUserByUUIDRow, error)
	IsExistProfile(ctx context.Context, userID int32) (bool, error)
	IsUserActive(ctx context.Context, userID int32) (bool, error)
	UpdateProfileAvatarByUserId(ctx context.Context, arg UpdateProfileAvatarByUserIdParams) (UpdateProfileAvatarByUserIdRow, error)
	UpdateProfileByUserId(ctx context.Context, arg UpdateProfileByUserIdParams) (UpdateProfileByUserIdRow, error)
}

var _ Querier = (*Queries)(nil)
