syntax = "proto3";

package proto;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

option go_package = "internal/gen-proto/user;user_proto";

service UserService {
  rpc SearchUserByUUID(SearchUserByUUIDRequest) returns (SearchUserByUUIDResponse);
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
  rpc DeleteUserByUserID(DeleteUserRequest) returns (DeleteUserResponse);
  rpc ActiveUser(EnableUserRequest) returns (EnableUserResponse);
  rpc IsExistProfile(IsExistProfileRequest) returns (IsExistProfileResponse);
  rpc CreateProfile(CreateProfileRequest) returns (CreateProfileResponse);
  rpc DisableUserByUserID(DisableUserRequest) returns (DisableUserResponse);
  rpc GetProfile(GetProfileRequest) returns (GetProfileResponse);
  rpc GetProfileByUserID(GetProfileByUserIDRequest) returns (GetProfileByUserIDResponse);
  rpc GetProfileByUserIDs(GetProfileByUserIDsRequest) returns (GetProfileByUserIDsResponse);
  rpc VerifyIDTokenOTP(VerifyIDTokenOTPRequest) returns (VerifyIDTokenOTPResponse);
  rpc UpdateProfile(UpdateProfileRequest) returns (UpdateProfileResponse);
  rpc UpdateAvatar(UpdateAvatarRequest) returns (UpdateAvatarResponse);
  rpc ReportUserImage(ReportUserImageRequest) returns (ReportUserImageResponse);
}

message GetProfileByUserIDsRequest {
  repeated int32 user_ids = 1 [
    (buf.validate.field).repeated.max_items = 10,
    (buf.validate.field).repeated.items.int32.gt = 0
  ];
}

message GetProfileByUserIDsResponse {
  message UserProfile {
    int32 user_id = 1;
    string name = 2;
    optional string avatar_url = 3;
  }

  repeated UserProfile profiles = 1;
}

message SearchUserByUUIDRequest {
  string target_user_uuid = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];

  int32 current_user_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).int32.gt = 0
  ];
}

message SearchUserByUUIDResponse {
  int32 user_id = 1;
  string name = 2;
  optional string avatar_url = 3;
}

message CreateUserRequest {
  string display_name = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1,
    (buf.validate.field).string.max_len = 100
  ];
}

message CreateUserResponse {
  int32 user_id = 1;
  string message = 2;
}

message EnableUserRequest {
  int32 user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).int32.gt = 0
  ];
}

message EnableUserResponse {
  bool success = 1;
  string message = 2;
}

message IsExistProfileRequest {
  int32 user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).int32.gt = 0
  ];
}

message IsExistProfileResponse {
  bool exists = 1;
  string message = 2;
}

message DeleteUserRequest {
  int32 user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).int32.gt = 0
  ];
}

message DeleteUserResponse {
  bool success = 1;
  string message = 2;
}

message CreateProfileRequest {
  int32 user_id = 1 [
    (buf.validate.field).required = true
  ];
  string name = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 2
  ];
  string email = 3 [
    (buf.validate.field).string.email = false,
    (buf.validate.field).string.max_len = 254,
    (buf.validate.field).string.min_len = 3
  ];
  string birthday = 4 [
  (buf.validate.field).required = false,
  (buf.validate.field).string.pattern = "^$|^(19|20)\\d\\d-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$"
  
];

  string avatar_url = 5;
}

message CreateProfileResponse {
  bool success = 1;
  string message = 2;
}

message DisableUserRequest {
  int32 user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).int32.gt = 0
  ];
}

message DisableUserResponse {
  bool success = 1;
  string message = 2;
}

message GetProfileRequest {
  int32 user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).int32.gt = 0
  ];
}

message GetProfileResponse {
  string uuid = 1;
  optional string name = 2;
  string email = 3;
  optional string birthday = 4;
  optional string phone = 5;
  optional string avatar_url = 6;
  google.protobuf.Timestamp updated_at = 7;
}

message GetProfileByUserIDRequest {
  int32 target_user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).int32.gt = 0
  ];

  int32 current_user_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).int32.gt = 0
  ];
}

message GetProfileByUserIDResponse {
  int32 user_id = 1;
  string name = 2;
  optional string birthday = 3;
  optional string avatar_url = 4;
}

message VerifyIDTokenOTPRequest {
  string id_token = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1,
    (buf.validate.field).string.pattern = "^(?!\\s*$).+"
  ];
}

message VerifyIDTokenOTPResponse {
  bool valid = 1;
  string verified_phone = 2;
  string message = 3;
}

message UpdateProfileRequest {
  int32 user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).int32.gt = 0
  ];
  optional string name = 2 [
    (buf.validate.field).string.min_len = 1,
    (buf.validate.field).string.max_len = 100,
    (buf.validate.field).string.pattern = "^(?!\\s*$).+"
  ];
  optional string birthday = 3 [
    (buf.validate.field).string.pattern = "^$|^(19|20)\\d\\d-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$"
  ];

  optional string phone = 4;
}

message UpdateProfileResponse {
  string message = 1;
}

message UpdateAvatarRequest {
  int32 user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).int32.gt = 0
  ];

  string avatar_url = 2 [
    (buf.validate.field).required = true
  ];
}

message UpdateAvatarResponse {
  string message = 1;
}

message ReportUserImageRequest {
  string uuid = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];

  string bucket = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1,
    (buf.validate.field).string.pattern = "^(?!\\s*$).+"
  ];

  string name = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1,
    (buf.validate.field).string.pattern = "^(?!\\s*$).+",
    (buf.validate.field).string.uuid = true
  ];
}

message ReportUserImageResponse {
  string message = 1;
}




