// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friend.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const acceptFriendRequestById = `-- name: AcceptFriendRequestById :one
update friend_requests
set is_accepted = true
where request_id = $1 and receiver_id = $2 and is_accepted = false
returning sender_id, receiver_id, is_accepted
`

type AcceptFriendRequestByIdParams struct {
	RequestID  int32 `json:"request_id"`
	ReceiverID int32 `json:"receiver_id"`
}

type AcceptFriendRequestByIdRow struct {
	SenderID   int32 `json:"sender_id"`
	ReceiverID int32 `json:"receiver_id"`
	IsAccepted bool  `json:"is_accepted"`
}

func (q *Queries) AcceptFriendRequestById(ctx context.Context, arg AcceptFriendRequestByIdParams) (AcceptFriendRequestByIdRow, error) {
	row := q.db.QueryRow(ctx, acceptFriendRequestById, arg.RequestID, arg.ReceiverID)
	var i AcceptFriendRequestByIdRow
	err := row.Scan(&i.SenderID, &i.ReceiverID, &i.IsAccepted)
	return i, err
}

const addFriendById = `-- name: AddFriendById :one
select f.status::boolean, f.message::text from send_friend_request($1, $2) as f
`

type AddFriendByIdParams struct {
	SenderUserID   int32 `json:"sender_user_id"`
	ReceiverUserID int32 `json:"receiver_user_id"`
}

type AddFriendByIdRow struct {
	FStatus  bool   `json:"f_status"`
	FMessage string `json:"f_message"`
}

func (q *Queries) AddFriendById(ctx context.Context, arg AddFriendByIdParams) (AddFriendByIdRow, error) {
	row := q.db.QueryRow(ctx, addFriendById, arg.SenderUserID, arg.ReceiverUserID)
	var i AddFriendByIdRow
	err := row.Scan(&i.FStatus, &i.FMessage)
	return i, err
}

const createFriendShip = `-- name: CreateFriendShip :execresult
insert into friendships (user1_id, user2_id, established_at)
values (least($1::int, $2::int), greatest($1::int, $2::int), $3)
on conflict(user1_id, user2_id)
do update set 
    established_at = excluded.established_at
where friendships.established_at < excluded.established_at
`

type CreateFriendShipParams struct {
	SenderUserID   int32     `json:"sender_user_id"`
	ReceiverUserID int32     `json:"receiver_user_id"`
	EstablishedAt  time.Time `json:"established_at"`
}

func (q *Queries) CreateFriendShip(ctx context.Context, arg CreateFriendShipParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createFriendShip, arg.SenderUserID, arg.ReceiverUserID, arg.EstablishedAt)
}

const deleteUserStatus = `-- name: DeleteUserStatus :exec
delete from user_status where user_id = $1
`

func (q *Queries) DeleteUserStatus(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserStatus, userID)
	return err
}

const getDisabledUser = `-- name: GetDisabledUser :one
select user_id, status, updated_at from user_status where user_id = $1
`

func (q *Queries) GetDisabledUser(ctx context.Context, userID int32) (UserStatus, error) {
	row := q.db.QueryRow(ctx, getDisabledUser, userID)
	var i UserStatus
	err := row.Scan(&i.UserID, &i.Status, &i.UpdatedAt)
	return i, err
}

const getFriendList = `-- name: GetFriendList :many
select 
    (case 
        when user1_id = $1 then user2_id 
        else user1_id
    end)::int as friend_ids
from friendships
where 
    (user1_id = $1 and user2_id > $2) 
    or
    (user2_id = $1 and user1_id > $2)
order by friend_ids
limit 10
`

type GetFriendListParams struct {
	CurrentUserID int32 `json:"current_user_id"`
	LastFriendID  int32 `json:"last_friend_id"`
}

func (q *Queries) GetFriendList(ctx context.Context, arg GetFriendListParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getFriendList, arg.CurrentUserID, arg.LastFriendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var friend_ids int32
		if err := rows.Scan(&friend_ids); err != nil {
			return nil, err
		}
		items = append(items, friend_ids)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInfoRelationship = `-- name: GetInfoRelationship :one
select     
    -- Friend request status (if exists)
    fr.sender_id,
    fr.is_accepted,
    
    -- Friendship status (if exists)
    (f.user1_id is not null)::boolean as is_friend

from (select 1) as dummy

left join friend_requests fr 
    on (fr.sender_id = $1 and fr.receiver_id = $2)
    or (fr.sender_id = $2 and fr.receiver_id = $1)

left join friendships f
    on (f.user1_id = LEAST($1, $2) and f.user2_id = GREATEST($1, $2))

where $2 <> $1
`

type GetInfoRelationshipParams struct {
	CurrentUserID int32 `json:"current_user_id"`
	TargetUserID  int32 `json:"target_user_id"`
}

type GetInfoRelationshipRow struct {
	SenderID   *int32 `json:"sender_id"`
	IsAccepted *bool  `json:"is_accepted"`
	IsFriend   bool   `json:"is_friend"`
}

// Get user info with friendship/friend request status
// Check if there's a pending/accepted friend request
// Check if already friends
func (q *Queries) GetInfoRelationship(ctx context.Context, arg GetInfoRelationshipParams) (GetInfoRelationshipRow, error) {
	row := q.db.QueryRow(ctx, getInfoRelationship, arg.CurrentUserID, arg.TargetUserID)
	var i GetInfoRelationshipRow
	err := row.Scan(&i.SenderID, &i.IsAccepted, &i.IsFriend)
	return i, err
}

const getPendingFriendRequests = `-- name: GetPendingFriendRequests :many
select request_id, sender_id, send_at
from friend_requests
where receiver_id = $1 and is_accepted = false and request_id > $2
order by send_at desc
limit 10
`

type GetPendingFriendRequestsParams struct {
	CurrentUserID int32 `json:"current_user_id"`
	LastRequestID int32 `json:"last_request_id"`
}

type GetPendingFriendRequestsRow struct {
	RequestID int32     `json:"request_id"`
	SenderID  int32     `json:"sender_id"`
	SendAt    time.Time `json:"send_at"`
}

func (q *Queries) GetPendingFriendRequests(ctx context.Context, arg GetPendingFriendRequestsParams) ([]GetPendingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, getPendingFriendRequests, arg.CurrentUserID, arg.LastRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingFriendRequestsRow{}
	for rows.Next() {
		var i GetPendingFriendRequestsRow
		if err := rows.Scan(&i.RequestID, &i.SenderID, &i.SendAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSentFriendRequests = `-- name: GetSentFriendRequests :many
select request_id, receiver_id, send_at
from friend_requests
where sender_id = $1 and is_accepted = false and request_id > $2
order by send_at desc
limit 10
`

type GetSentFriendRequestsParams struct {
	CurrentUserID int32 `json:"current_user_id"`
	LastRequestID int32 `json:"last_request_id"`
}

type GetSentFriendRequestsRow struct {
	RequestID  int32     `json:"request_id"`
	ReceiverID int32     `json:"receiver_id"`
	SendAt     time.Time `json:"send_at"`
}

func (q *Queries) GetSentFriendRequests(ctx context.Context, arg GetSentFriendRequestsParams) ([]GetSentFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, getSentFriendRequests, arg.CurrentUserID, arg.LastRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSentFriendRequestsRow{}
	for rows.Next() {
		var i GetSentFriendRequestsRow
		if err := rows.Scan(&i.RequestID, &i.ReceiverID, &i.SendAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectFriendRequestById = `-- name: RejectFriendRequestById :execresult
delete from friend_requests
where request_id = $1 and receiver_id = $2 and is_accepted=false
`

type RejectFriendRequestByIdParams struct {
	RequestID  int32 `json:"request_id"`
	ReceiverID int32 `json:"receiver_id"`
}

func (q *Queries) RejectFriendRequestById(ctx context.Context, arg RejectFriendRequestByIdParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, rejectFriendRequestById, arg.RequestID, arg.ReceiverID)
}

const saveUserStatus = `-- name: SaveUserStatus :execresult
insert into user_status (
    user_id,
    status,
    updated_at
)
values ($1, $2, $3)
on conflict (user_id)
do update set
    status = excluded.status,
    updated_at = excluded.updated_at
where user_status.updated_at < excluded.updated_at
`

type SaveUserStatusParams struct {
	UserID    int32     `json:"user_id"`
	Status    int16     `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) SaveUserStatus(ctx context.Context, arg SaveUserStatusParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, saveUserStatus, arg.UserID, arg.Status, arg.UpdatedAt)
}
