// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	AcceptFriendRequestById(ctx context.Context, arg AcceptFriendRequestByIdParams) (AcceptFriendRequestByIdRow, error)
	AddFriendById(ctx context.Context, arg AddFriendByIdParams) (AddFriendByIdRow, error)
	CreateFriendShip(ctx context.Context, arg CreateFriendShipParams) (pgconn.CommandTag, error)
	DeleteUserStatus(ctx context.Context, userID int32) error
	GetDisabledUser(ctx context.Context, userID int32) (UserStatus, error)
	GetFriendList(ctx context.Context, arg GetFriendListParams) ([]int32, error)
	// Get user info with friendship/friend request status
	// Check if there's a pending/accepted friend request
	// Check if already friends
	GetInfoRelationship(ctx context.Context, arg GetInfoRelationshipParams) (GetInfoRelationshipRow, error)
	GetPendingFriendRequests(ctx context.Context, arg GetPendingFriendRequestsParams) ([]GetPendingFriendRequestsRow, error)
	GetSentFriendRequests(ctx context.Context, arg GetSentFriendRequestsParams) ([]GetSentFriendRequestsRow, error)
	RejectFriendRequestById(ctx context.Context, arg RejectFriendRequestByIdParams) (pgconn.CommandTag, error)
	SaveUserStatus(ctx context.Context, arg SaveUserStatusParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
