// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type UserInfo struct {
	UserID     int32     `json:"user_id"`
	DeviceUuid uuid.UUID `json:"device_uuid"`
	PushToken  string    `json:"push_token"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type UserStatus struct {
	UserID    int32     `json:"user_id"`
	Status    int16     `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}
