// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notify.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const createFCMNotification = `-- name: CreateFCMNotification :execresult
insert into user_info(
    user_id,
    push_token,
    device_uuid
)
values ($1, $2, $3)
on conflict (user_id, device_uuid)
do update set
    push_token = excluded.push_token,
    updated_at = now()
`

type CreateFCMNotificationParams struct {
	UserID     int32     `json:"user_id"`
	PushToken  string    `json:"push_token"`
	DeviceUuid uuid.UUID `json:"device_uuid"`
}

func (q *Queries) CreateFCMNotification(ctx context.Context, arg CreateFCMNotificationParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createFCMNotification, arg.UserID, arg.PushToken, arg.DeviceUuid)
}

const deleteUserStatus = `-- name: DeleteUserStatus :exec
delete from user_status where user_id = $1
`

func (q *Queries) DeleteUserStatus(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserStatus, userID)
	return err
}

const getDisabledUser = `-- name: GetDisabledUser :one
select user_id, status, updated_at from user_status where user_id = $1
`

func (q *Queries) GetDisabledUser(ctx context.Context, userID int32) (UserStatus, error) {
	row := q.db.QueryRow(ctx, getDisabledUser, userID)
	var i UserStatus
	err := row.Scan(&i.UserID, &i.Status, &i.UpdatedAt)
	return i, err
}

const getUserInfo = `-- name: GetUserInfo :one
select user_id, device_uuid, push_token, created_at, updated_at from user_info where user_id = $1 and device_uuid = $2
`

type GetUserInfoParams struct {
	UserID     int32     `json:"user_id"`
	DeviceUuid uuid.UUID `json:"device_uuid"`
}

func (q *Queries) GetUserInfo(ctx context.Context, arg GetUserInfoParams) (UserInfo, error) {
	row := q.db.QueryRow(ctx, getUserInfo, arg.UserID, arg.DeviceUuid)
	var i UserInfo
	err := row.Scan(
		&i.UserID,
		&i.DeviceUuid,
		&i.PushToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserInfoByUserID = `-- name: GetUserInfoByUserID :many
select push_token, device_uuid from user_info where user_id = $1
`

type GetUserInfoByUserIDRow struct {
	PushToken  string    `json:"push_token"`
	DeviceUuid uuid.UUID `json:"device_uuid"`
}

func (q *Queries) GetUserInfoByUserID(ctx context.Context, userID int32) ([]GetUserInfoByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getUserInfoByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserInfoByUserIDRow{}
	for rows.Next() {
		var i GetUserInfoByUserIDRow
		if err := rows.Scan(&i.PushToken, &i.DeviceUuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveUserStatus = `-- name: SaveUserStatus :execresult
insert into user_status (
    user_id,
    status,
    updated_at
)
values ($1, $2, $3)
on conflict (user_id)
do update set
    status = excluded.status,
    updated_at = excluded.updated_at
where user_status.updated_at < excluded.updated_at
`

type SaveUserStatusParams struct {
	UserID    int32     `json:"user_id"`
	Status    int16     `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) SaveUserStatus(ctx context.Context, arg SaveUserStatusParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, saveUserStatus, arg.UserID, arg.Status, arg.UpdatedAt)
}
