// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CreateFCMNotification(ctx context.Context, arg CreateFCMNotificationParams) (pgconn.CommandTag, error)
	DeleteUserStatus(ctx context.Context, userID int32) error
	GetDisabledUser(ctx context.Context, userID int32) (UserStatus, error)
	GetUserInfo(ctx context.Context, arg GetUserInfoParams) (UserInfo, error)
	GetUserInfoByUserID(ctx context.Context, userID int32) ([]GetUserInfoByUserIDRow, error)
	SaveUserStatus(ctx context.Context, arg SaveUserStatusParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
